import { getProjectName } from "@/core/newReadDocData";
import Link from "next/link";



export default async function Docs() {
    const projectName = await getProjectName()

    return (
        <div className="flex flex-col w-full min-h-full p-12">
            <div className="flex flex-col mb-8 gap-4">
                <h1 className="text-3xl font-bold"> {projectName} </h1>
                <p> This documentation is autogenerated by <Link href="https://github.com/akikaki-bot/auto-generate-typescript-definition-index">this tool</Link>. So it may have inaccuracies.</p>
            </div>
            <div className="flex flex-col gap-2">
                <h2 className="text-2xl font-bold"> Select properties from sidebar. </h2>
            </div>
        </div>
    )
}