import Link from "next/link";

export default function Home() {
	return (
		<main className="flex min-h-screen flex-col items-center p-24">
			<h1 className="text-5xl font-bold mb-8"> Welcome to DocName! </h1>
			<p className="text-lg"> This is a documentation of DocName. </p>
			<div className="flex flex-row gap-4 items-center mt-8">
				<Link
					href="/docs" 
					className="text-xl border-green-500 border px-4 py-2 rounded-lg hover:bg-green-200 transition"
				>
					Documentation
				</Link>
				<Link
					href="https://github.com/your-repo"
					className="text-xl border-green-500 border px-4 py-2 rounded-lg hover:bg-green-200 transition"
				>
					Github
				</Link>
			</div>
			<div className="flex flex-col items-center mt-8">
				<p className="mt-4 text-center max-w-md"> This documentation is autogenerated by <a className="text-green-600 underline" href="https://github.com/akikaki-bot/auto-generate-typescript-definition-index">akikaki-bot/auto-generate-typescript-definition-index</a></p>
			</div>
		</main>
	);
}
